spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGO_URI}
    database: privatenotes
  output:
    ansi:
      enabled: NEVER
logging:
  level:
    root: WARN
    com.luispiquinrey.backend: INFO
