spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGO_URI}
    database: privatenotes
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: INFO
    com.luispiquinrey.backend: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web: DEBUG
