name: Build Project with SonarQube (Test profile)

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    environment: DEV_ENVIRONMENT

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build, test and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          ./mvnw clean verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.organization=messafy
          -Dsonar.projectKey=messafy_backend

